### ISSUE TITLE
YAML configuration : TOOL1

### ISSUE THREAD

**Issue by kumardeepak** [project-anuvaad/corpus-tools#5]
1. What is "use_tokens_from_db" field. Can't we put all the configuration in the YAML including the negative and positive token?

2. What will be the impact on the system ?

3.

**Comment by iostream04** [comment]
1. It is a concept of storing tokens which are previously extracted from already processed paragraphs.
2. We get positive tokens after processing the paragraphs. If you are talking about previously extracted positive tokens ? We can provide them also in a csv file as we are providing a csv file for negative tokens.
3. Putting pos and Neg token in config file will not create any feasibility issue but can increase the size of config file and also increase the probability of error in config file.

**Comment by iostream04** [comment]
commit id : 46b174d
